global:

  scrape_interval:     15s # Default is every 1 minute.
  scrape_timeout:      10s # Default is 10s
  evaluation_interval: 15s # Default is every 1 minute.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      demo: 'demo-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'overwritten-default'
    consul_sd_configs:
      - server:   '192.168.31.51:8500'
        # services: ['prometheus', 'node-exporter', 'grafana', 'cadvisor', 'rabbitmq-exporter']
        services: []
    relabel_configs:
      - source_labels: ['__meta_consul_tags']
        regex: .*,prometheus-target,.*
        action: keep
      - source_labels: ['__meta_consul_tags']
        regex: .*,production,.*
        action: keep
      # - source_labels: ['__meta_consul_service']
      #   regex: prometheus\-(.+)
      #   replacement: '${1}'
      #   target_label: 'job'
      - source_labels: [__meta_consul_service]
        target_label: job
      - source_labels: ['__meta_consul_node']
        target_label:  'instance'
        regex:         '(.*)'
        replacement:   '$1'
      - source_labels: ['__meta_consul_service']
        target_label: service
        # regex:         '(.*)'
        # replacement:   '$1'

      - source_labels: ['__meta_consul_tags']
        regex:         ',(production|canary),'
        target_label:  'group'
        replacement:   '$1'
      # - source_labels: ['__meta_consul_tags']
      #   regex: .*prometheus-target.*
      #   action: drop

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx] # 和blackbox中配置的模块名要对应blackbox配置文件中定义的
    static_configs:
      - targets:
        - baidu.com # 检测目标
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.31.51:9115  # This is your blackbox exporter.

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'