logLevel = "DEBUG" # DEBUG, INFO, WARN, ERROR, FATAL, PANIC

InsecureSkipVerify = true 

defaultEntryPoints = ["https", "http"]

[api]
  entryPoint = "traefik"
  dashboard = true
  # address = ":8080"
  debug = true

[entryPoints]
  [entryPoints.http]
    address = ":80"

[docker]
    endpoint = "unix:///var/run/docker.sock"
    domain = "docker.local"
    watch = true
    # false will hide all docker containers that don't have explicitly, set container label to "enable"
    exposedbydefault = true

[metrics]
    [metrics.prometheus]

# [tracing]
#    [tracing.jaeger]
