{
 "title": "coinmarketcap-single",
 "description": "This is a dashboard that shows some stats and information on cryptocurrencies, such as Bitcoin, Ethereum, Litecoin, etc. This data is gathered from http://www.coinmarketcap.com. It display statistics on price in USD, Bitcoin, trends, etc.\r\n\r\nIt is intended to be run with Prometheus and the Coinmarketcap exporter (https://github.com/bonovoxly/coinmarketcap-exporter).\r\n\r\n",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "name", "label": "name", "query": "label_values(name)" }
  ]
 },
 "panels": [
  {
   "title": "$name - USD",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "coin_market_price_usd{name=\"$name\"}"
    }
   ]
  },
  {
   "title": "$name - Percent Change in USD",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(coin_market_price_usd{name=~\"$name\"} - coin_market_price_usd{name=~\"$name\"} offset 24h) / coin_market_price_usd{name=~\"$name\"}"
    }
   ]
  },
  {
   "title": "$name - Price in Bitcoin",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "coin_market_price_btc{name=\"$name\"}"
    }
   ]
  },
  {
   "title": "$name - Percent Change in BTC",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(coin_market_price_btc{name=~\"$name\"} - coin_market_price_btc{name=~\"$name\"} offset 24h) / coin_market_price_btc{name=~\"$name\"}"
    }
   ]
  },
  {
   "title": "$name - Volume",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "coin_market_24h_volume_usd{name=\"$name\"}"
    }
   ]
  },
  {
   "title": "$name - Market Cap",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "coin_market_market_cap_usd{name=\"$name\"}"
    }
   ]
  },
  {
   "title": "$name Price in USD",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "coin_market_price_usd{name=~\"$name\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "$name Price in Bitcoin",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "coin_market_price_btc{name=~\"$name\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "$name Price Difference in USD from 24 hours ago",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "coin_market_price_usd{name=~\"$name\"} - coin_market_price_usd{name=~\"$name\"} offset 24h",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "$name Difference in BTC price from 24 hours ago",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "coin_market_price_btc{name=~\"$name\"} - coin_market_price_btc{name=~\"$name\"} offset 24h",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}