{
 "title": "GitHub Stats",
 "description": "A docker stack which uses Grafana to collect GitHub statistics for selected Repositories",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Docker Stars",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "github_repo_stars{repo=\"moby\"}",
     "legendFormat": "{{stars}}"
    }
   ]
  },
  {
   "title": "Docker Open Issues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "github_repo_open_issues{repo=\"moby\"}",
     "legendFormat": "{{Open Issues}}"
    }
   ]
  },
  {
   "title": "Docker Forks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "github_repo_forks{repo=\"moby\"}",
     "legendFormat": "{{Forks}}"
    }
   ]
  },
  {
   "title": "Stars of  kubernetes/kubernetes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "github_repo_stars{repo=\"kubernetes\"}",
     "legendFormat": "{{stars}}"
    }
   ]
  },
  {
   "title": "Open Issues of kubernetes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "github_repo_open_issues{repo=\"kubernetes\"}",
     "legendFormat": "{{Open Issues}}"
    }
   ]
  },
  {
   "title": "Forks of kubernetes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "github_repo_forks{repo=\"kubernetes\"}",
     "legendFormat": "{{Forks}}"
    }
   ]
  },
  {
   "title": "Stars of  prometheus/prometheus",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "github_repo_stars{repo=\"prometheus\"}",
     "legendFormat": "{{stars}}"
    }
   ]
  },
  {
   "title": "Open issues of  prometheus/prometheus",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "github_repo_open_issues{repo=\"prometheus\"}",
     "legendFormat": "{{stars}}"
    }
   ]
  },
  {
   "title": "Forks of prometheus",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "github_repo_forks{repo=\"prometheus\"}",
     "legendFormat": "{{Forks}}"
    }
   ]
  },
  {
   "title": "Stars of  grafana",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "github_repo_stars{repo=\"grafana\"}",
     "legendFormat": "{{stars}}"
    }
   ]
  },
  {
   "title": "Open issues of  grafana",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "github_repo_open_issues{repo=\"grafana\"}",
     "legendFormat": "{{stars}}"
    }
   ]
  },
  {
   "title": "Forks of grafana",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "github_repo_forks{repo=\"grafana\"}",
     "legendFormat": "{{Forks}}"
    }
   ]
  }
 ]
}